- name: Install Python libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
  - PyMySQL
  - cryptography

- name: Disable current nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: Enable current nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.package:
    name: "{{ item }}"
    state: installed
  loop:
  - nodejs
  - mysql

- name: create user
  ansible.builtin.user:
    name: expense

- name: create /app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: unzip application code
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app
    state: present

- name: Copy backend service 
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service
  
- name: import mysql data
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql.pavancloud5.online
    target: /app/schema/backend.sql

- name: daemon_reload restart
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    daemon_reload: true
    enabled: true